[[channel]]
name = "huron"
description = "Projects by hyperspace labs"
root = "./index"
sync.command = ["git", "pull"]
post.command = ["python3", "publish.py"]


[[protocol]]
name = "git"
description = "Download projects using git"
command = ["git", "clone", "{{ orbit.project.source }}", "-b", "{{ orbit.project.version }}"]
patterns = ["*.git"]