[ip]
name = "gates"
uuid = "agduyk4nls7aw0tdc5946fzde"
version = "1.0.2"
channels = ["hyperspace-labs"]
public = ["rtl"]

[ip.source]
url = "https://github.com/hyperspace-labs/gates/archive/{{orbit.ip.version}}.zip"
